// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// axisepmgp
Rcpp::List axisepmgp(arma::vec m, arma::mat K, arma::vec lb, arma::vec ub);
RcppExport SEXP _epmgp_axisepmgp(SEXP mSEXP, SEXP KSEXP, SEXP lbSEXP, SEXP ubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ub(ubSEXP);
    rcpp_result_gen = Rcpp::wrap(axisepmgp(m, K, lb, ub));
    return rcpp_result_gen;
END_RCPP
}
// epmgp
Rcpp::List epmgp(arma::vec m, arma::mat K, arma::mat C, arma::vec lb, arma::vec ub, int max_steps);
RcppExport SEXP _epmgp_epmgp(SEXP mSEXP, SEXP KSEXP, SEXP CSEXP, SEXP lbSEXP, SEXP ubSEXP, SEXP max_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ub(ubSEXP);
    Rcpp::traits::input_parameter< int >::type max_steps(max_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(epmgp(m, K, C, lb, ub, max_steps));
    return rcpp_result_gen;
END_RCPP
}
// erfcx
double erfcx(double x);
RcppExport SEXP _epmgp_erfcx(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(erfcx(x));
    return rcpp_result_gen;
END_RCPP
}
// trunc_norm_moments
Rcpp::List trunc_norm_moments(arma::vec lb_in, arma::vec ub_in, arma::vec mu_in, arma::vec sigma_in);
RcppExport SEXP _epmgp_trunc_norm_moments(SEXP lb_inSEXP, SEXP ub_inSEXP, SEXP mu_inSEXP, SEXP sigma_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lb_in(lb_inSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ub_in(ub_inSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_in(mu_inSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_in(sigma_inSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_norm_moments(lb_in, ub_in, mu_in, sigma_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_epmgp_axisepmgp", (DL_FUNC) &_epmgp_axisepmgp, 4},
    {"_epmgp_epmgp", (DL_FUNC) &_epmgp_epmgp, 6},
    {"_epmgp_erfcx", (DL_FUNC) &_epmgp_erfcx, 1},
    {"_epmgp_trunc_norm_moments", (DL_FUNC) &_epmgp_trunc_norm_moments, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_epmgp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
