# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

erfcx <- function(x) {
    .Call(`_epmgp_erfcx`, x)
}

trunc_norm_moments <- function(lb_in, ub_in, mu_in, sigma_in) {
    .Call(`_epmgp_trunc_norm_moments`, lb_in, ub_in, mu_in, sigma_in)
}

axisepmgp <- function(m, K, lb, ub) {
    .Call(`_epmgp_axisepmgp`, m, K, lb, ub)
}

