# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aug_epmgp <- function(m, K, lb, ub, max_steps, p) {
    .Call(`_epmgp_aug_epmgp`, m, K, lb, ub, max_steps, p)
}

axisepmgp <- function(m, K, lb, ub) {
    .Call(`_epmgp_axisepmgp`, m, K, lb, ub)
}

epmgp <- function(m, K, C, lb, ub, max_steps) {
    .Call(`_epmgp_epmgp`, m, K, C, lb, ub, max_steps)
}

sample_epmh <- function(n_samples, ep_mean, ep_chol, F, g, initial) {
    .Call(`_epmgp_sample_epmh`, n_samples, ep_mean, ep_chol, F, g, initial)
}

seq_epmgp <- function(m, K, Kinv, lb, ub, max_steps) {
    .Call(`_epmgp_seq_epmgp`, m, K, Kinv, lb, ub, max_steps)
}

range_intersection <- function(first, second) {
    .Call(`_epmgp_range_intersection`, first, second)
}

sample_epess <- function(n_samples, ep_mean, ep_chol, F, g, J, N, initial, verbose) {
    .Call(`_epmgp_sample_epess`, n_samples, ep_mean, ep_chol, F, g, J, N, initial, verbose)
}

test_wall_hit <- function(nu, initial, ep_mean, ep_chol, F, g, J, N) {
    .Call(`_epmgp_test_wall_hit`, nu, initial, ep_mean, ep_chol, F, g, J, N)
}

erfcx <- function(x) {
    .Call(`_epmgp_erfcx`, x)
}

trunc_norm_moments <- function(lb_in, ub_in, mu_in, sigma_in) {
    .Call(`_epmgp_trunc_norm_moments`, lb_in, ub_in, mu_in, sigma_in)
}

